# Generated by Django 5.0.4 on 2024-05-22 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_alter_product_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
