# Generated by Django 5.0.4 on 2024-06-03 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0009_remove_user_user_password_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
