# Generated by Django 5.0.4 on 2024-06-03 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0010_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
