# Generated by Django 5.0.6 on 2024-06-12 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0015_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_status',
        ),
    ]
