# Generated by Django 5.0.6 on 2024-06-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0018_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_quantiy',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
