# Generated by Django 5.0.6 on 2024-06-13 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0019_product_product_quantiy_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_quantiy',
        ),
        migrations.AddField(
            model_name='product',
            name='product_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
