# Generated by Django 5.0.6 on 2024-06-14 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0021_remove_orderdetail_product_orderdetail_item_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='item_name',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project_app.product'),
            preserve_default=False,
        ),
    ]
