# Generated by Django 5.0.6 on 2024-06-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0024_order_receiver_address_order_receiver_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cod', 'Cash On Delivery'), ('online', 'Online Payment')], max_length=10, null=True),
        ),
    ]
