# Generated by Django 5.0.6 on 2024-06-16 13:44

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0026_alter_user_options_user_created_at'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('product_name'), name='unique_product_name_case_insensitive'),
        ),
    ]
